### PR TITLE
Various minor improvements

### PR DESCRIPTION
**Pull request by ko-dever**
As title say, just some minor improvements. (if performance matters)

### CODE REVIEW

**Review by siggy — COMMENTED** [review]
@zanot thank you for the updates, really appreciate the contributions.

i think i tried using `let` before and it broke on osx safari and ios safari.

on osx safari i get:
screen shot 2016-09-14 at 6 10 15 pm

i'm testing with:
https://cdn.rawgit.com/zanot/beatboxer/50b86763c1cc849d54e588c766972d035f713e7a/index.htm

looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let, i'm kind of surprised to see safari support listed as `?`

**Comment by siggy** [comment]
oops i meant: https://cdn.rawgit.com/zanot/beatboxer/50b86763c1cc849d54e588c766972d035f713e7a/index.html

**Comment by ko-dever** [comment]
Oops you are right, I replaced `let` statements.
For a better overview of ES6 compatibility I check this site :
https://kangax.github.io/compat-table/es6/

**Comment by siggy** [comment]
for testing: https://cdn.rawgit.com/zanot/beatboxer/fa7fb1787619b93175a28286b6552d095a8cf55d/index.html

**Review by siggy — APPROVED** [review]
Great work, thank you @zanot !

**Pull request merged**
